### ISSUE TITLE
Release code

### ISSUE THREAD

**Issue by jkooy** [rabeehk/compacter#1]
Hello,

Thanks for your awesome work. May I ask when will you release your code? That will of great help for us. Thanks!

**Comment by rabeehk** [comment]
Dear @jkooy 
I am currently working on adding more experiments, and I will release the codes by end of August. If you need to use it now, please have a look here 
https://github.com/anonymousxzy/compacter 
where we released the anonymous version of the codes. Please feel free to write me of any issues.
thank you.

**Comment by rabeehk** [comment]
Hi there,
I just added the codes. Sorry for the delay.
Best
Rabeeh
