### ISSUE TITLE
SAID issue 

### ISSUE THREAD

**Issue by muqeeth** [rabeehk/compacter#3]
Hi Rabeeh,
Thanks for releasing the code. We are trying out intrinsic SAID experiments in the paper. We are facing the following issue:
```    from seq2seq.projections.fwh_cuda import fast_walsh_hadamard_transform as fast_walsh_hadamard_transform_cuda
ImportError: cannot import name 'fast_walsh_hadamard_transform' from 'seq2seq.projections.fwh_cuda' (unknown location)```

We ran ```python setup.py install```.  Packages seems to install correctly.  Running ```bash scripts/intrinsic_said.sh``` is giving up the above issue.

**Comment by rabeehk** [comment]
Hi 
Apologies for my late reply, I recreated an environment and installed on GeForce RTX 3090 this works for me. Could you maybe run python setup.py develop on a GPU device? I think maybe you did not had access to GPU when compiling?

**Comment by rabeehk** [comment]
Also, from what I know, if you change the GPU type you need to recompile first, unless you add this line when compiling to make it work with other GPU types too:
TORCH_CUDA_ARCH_LIST="3.5;3.7;6.1;7.0;7.5;8.6+PTX"

**Comment by muqeeth** [comment]
Thanks for the reply. I am using A5000 GPU.  I uncommented the line TORCH_CUDA_ARCH_LIST="3.5;3.7;6.1;7.0;7.5;8.6+PTX" and ran python setup.py install file. It did not solve the issue. I am getting the same error as mentioned.  I didn't get what you meant as to having access to GPU when compiling? Is there a different command for compiling or python setup.py handles everything?

**Comment by rabeehk** [comment]
Hi
the setup.py is taking care of the whole installation. 
For adding this option, I was running it on terminal, TORCH_CUDA_ARCH_LIST="3.5;3.7;6.1;7.0;7.5;8.6+PTX", then run the setup, but this only helped me when I was running the codes on multiple GPU types, for your case I am guessing maybe the installation is not done properly, do you mind sending me your outputs when you run python setup.py develop

thanks

**Comment by muqeeth** [comment]
Are "python setup.py install" and "python setup.py develop" commands one and the same?

**Comment by rabeehk** [comment]
if you want to change a code, then if you run it with python setup.py develop your changes will be affected, if you run python setup.py install, then if you change the codes they wont have an impact.
Normally I use python setup.py develop, as I change baseline codes.

**Comment by muqeeth** [comment]
Running "python setup.py develop" helped. The code now runs fine on one GPU. Thanks! 

If I run the code on two gpus on the same server(same GPU type).  I get below error. How do I resolve this?
```
File "/fruitbasket/users/muqeeth/compacter/seq2seq/projections/intrinsic.py", line 248, in __call__
    ray = ray * self.intrinsic_parameter_said[index]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!
```

**Comment by rabeehk** [comment]
Hi
great, could you run the codes on 1 GPU, by setting the visible GPU ones? as the codes are only tested on 1 GPU

**Comment by muqeeth** [comment]
yes I can run on 1 GPU. Using two GPUs creates the issue I mentioned above.

**Comment by rabeehk** [comment]
Dear @muqeeth 
I dont think this works with multiple GPUs. I got the codes from FB authors, you might want to ask them if they have extended this for multi-gpu too

**Comment by muqeeth** [comment]
No worries, I guess one GPU is fine too, It runs on a GPU with 24GB memory. Thanks for helping out!

**Comment by rabeehk** [comment]
youre welcome

**Comment by CaffreyR** [comment]
Hi @muqeeth @rabeehk , I am checking the same SAID with you, I want to output the SAID, should I just run `bash scripts/intrinsic_said.sh`?  Many thanks!:)

**Comment by muqeeth** [comment]
Hey hi, I am guessing once we have the requirements installed, the above command should be good to go.

**Comment by CaffreyR** [comment]
Hi @muqeeth , actually I am wondering the SAID itself. Since the SAID is fixed in the config , I have to manually set it and get the accuracy that corresponding to it and change it again to get another to plot the Figure?
