### ISSUE TITLE
implementation issue

### ISSUE THREAD

**Issue by FredZZD** [rabeehk/compacter#6]
In your paper, there's a res connect in adapter module, but it was not implemented in the code. 
`
def forward(self, x):
        z = self.down_sampler(x)
        z = self.activation(z)
        output = self.up_sampler(z)
        return output 
`
![image](https://user-images.githubusercontent.com/45964230/155445997-43e06a30-58b3-43c5-be28-e3ca7289049b.png)
I wonder if it should be `return output + x`
thanks

**Comment by rabeehk** [comment]
Hi
thanks for the question, this is done in AdapterController module, please see https://github.com/rabeehk/compacter/blob/b210eef13f64ff6441186ee5a1cbf031b5918b94/seq2seq/adapters/adapter_controller.py#L115 
thanks

**Comment by FredZZD** [comment]
Got it, thanks a lot
