### ISSUE TITLE
How to output the intrinsic_dimension

### ISSUE THREAD

**Issue by CaffreyR** [rabeehk/compacter#9]
Hi @rabeehk , sorry to bother again. But may I ask how to output the intrinsic_dimension, since I run the bash `bash scripts/intrinsic_said.sh` , it just output the acc

**Comment by rabeehk** [comment]
Hi
you can set the dimension for SAID here https://github.com/rabeehk/compacter/blob/b210eef13f64ff6441186ee5a1cbf031b5918b94/seq2seq/training_args.py#L42 
So you fixed it in the start and then it is fixed.

Best
Rabeeh

**Comment by CaffreyR** [comment]
So I have to manually set it and get the accuracy that corresponding to it  and change it again to get another?

**Comment by rabeehk** [comment]
Hi @CaffreyR 
If you want to test another dimension, you need to pass it to the config/intrinsic_said.json https://github.com/rabeehk/compacter/blob/main/seq2seq/configs/intrinsic_said.json 

Also the running command is as you mentioned, please see the README in the github.

Best
Rabeeh

**Comment by CaffreyR** [comment]
Thanks a lot!
